CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 16 --split test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_both_x_detectron_upd --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_detectron_upd --recover_step 3 --img_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 16 --split test --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_both_x_detectron_upd --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_detectron_upd --recover_step 3 --txt_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 16 --split test --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_txt --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_txt --recover_step 6 --txt_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 16 --split test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_img_detectron_upd --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_img_detectron_upd --recover_step 6 --img_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 8 --split test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_both_x_detectron_upd --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_detectron_upd --recover_step 3 --use_x_distractors --img_filter_max_choices 20 --txt_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 8 --split test --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_both_x_detectron_upd --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_detectron_upd --recover_step 3 --use_x_distractors --txt_filter_max_choices 20 --img_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=0 python run_webqa_vinvl.py --new_segment_ids --train_batch_size 8 --split test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_both_x_vinvl_upd2 --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_vinvl_upd2 --recover_step 4 --use_x_distractors --img_filter_max_choices 20 &&
CUDA_VISIBLE_DEVICES=2 python run_webqa_vinvl.py --new_segment_ids --train_batch_size 16 --split test --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 4 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 1 --save_loss_curve --output_dir light_output/filter_both_x_vinvl_upd2 --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_vinvl_upd2 --recover_step 4 --use_x_distractors --txt_filter_max_choices 20 




CUDA_VISIBLE_DEVICES=2 python run_webqa_vinvl.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 4 --max_pred 50 --mask_prob 0.5 --learning_rate 1e-4 --gradient_accumulation_steps 2 --save_loss_curve --num_train_epochs 5 --output_dir light_output/vinvl_both_qa_qonly --ckpts_dir /data/yingshac/MMMHQA/ckpts/vinvl_both_qa_qonly --no_img_meta --no_img_content --no_txt_fact --recover_step 1 &&


CUDA_VISIBLE_DEVICES=1 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 4 --max_pred 50 --mask_prob 0.5 --learning_rate 1e-4 --gradient_accumulation_steps 2 --save_loss_curve --output_dir light_output/detectron_both_qa_qonly --ckpts_dir /data/yingshac/MMMHQA/ckpts/detectron_both_qa_qonly --no_img_meta --no_img_content --no_txt_fact --recover_step 1 &&


CUDA_VISIBLE_DEVICES=1 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 4 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir light_output/filter_img_detectron --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_img_detectron --recover_step 4 &&



CUDA_VISIBLE_DEVICES=1 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir light_output/filter_txt --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_txt --recover_step 8 &&
CUDA_VISIBLE_DEVICES=1 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir light_output/filter_txt --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_txt --recover_step 9 &&
CUDA_VISIBLE_DEVICES=1 python run_webqa_vinvl.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'filter' --num_workers 4 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir light_output/filter_both_x_vinvl --ckpts_dir /data/yingshac/MMMHQA/ckpts/filter_both_x_vinvl --recover_step 6

CUDA_VISIBLE_DEVICES=1 python eval.py --file detectron_both_qa_upd/qa_infr/test_qainfr_no_eval_-1_beam5_img_True_True_step11_img_dataset_0823_clean_te.tsv --Qcate_breakdown '["color"]' &&
CUDA_VISIBLE_DEVICES=1 python eval.py --file detectron_both_qa_upd/qa_infr/test_qainfr_no_eval_-1_beam5_img_True_True_step11_img_dataset_0823_clean_te.tsv --Qcate_breakdown '["shape"]' &&
CUDA_VISIBLE_DEVICES=1 python eval.py --file detectron_both_qa_upd/qa_infr/test_qainfr_no_eval_-1_beam5_img_True_True_step11_img_dataset_0823_clean_te.tsv --Qcate_breakdown '["number"]' &&
CUDA_VISIBLE_DEVICES=1 python eval.py --file detectron_both_qa_upd/qa_infr/test_qainfr_no_eval_-1_beam5_img_True_True_step11_img_dataset_0823_clean_te.tsv --Qcate_breakdown '["YesNo"]' &&
CUDA_VISIBLE_DEVICES=1 python eval.py --file detectron_both_qa_upd/qa_infr/test_qainfr_no_eval_-1_beam5_img_True_True_step11_img_dataset_0823_clean_te.tsv --Qcate_breakdown '["choose"]' &&
CUDA_VISIBLE_DEVICES=1 python eval.py --file detectron_both_qa_upd/qa_infr/test_qainfr_no_eval_-1_beam5_img_True_True_step11_img_dataset_0823_clean_te.tsv --Qcate_breakdown '["Others"]'