#CUDA_VISIBLE_DEVICES=2,3 python run_webqa.py --new_segment_ids --do_train --train_batch_size 128 --split train \
#--answer_provided_by 'img|txt' --task_to_learn 'filter' --num_workers 8 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 \
#--gradient_accumulation_steps 64 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_full_data \
#--local_rank 0 --global_rank 0 --world_size 2 &

#CUDA_VISIBLE_DEVICES=2,3 python run_webqa.py --new_segment_ids --do_train --train_batch_size 128 --split train \
#--answer_provided_by 'img|txt' --task_to_learn 'filter' --num_workers 8 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 \
#--gradient_accumulation_steps 64 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_full_data \
#--local_rank 1 --global_rank 1 --world_size 2
#CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 16 --split ood_test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 8 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --output_dir tmp/img_filter --recover_ori_ckpt &

#CUDA_VISIBLE_DEVICES=3 python run_webqa.py --new_segment_ids --train_batch_size 16 --split ood_test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 8 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --output_dir tmp/img_filter &

#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --train_batch_size 16 --split ind_test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 8 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --output_dir tmp/img_filter --recover_ori_ckpt &

#CUDA_VISIBLE_DEVICES=2 python run_webqa.py --new_segment_ids --train_batch_size 16 --split ind_test --answer_provided_by 'img' --task_to_learn 'filter' --num_workers 8 --max_pred 10 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --output_dir tmp/img_filter &

#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 1 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 2 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 3 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 4 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 5 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 6 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 7 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 8 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 9 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 10 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 11 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 12 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 13 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 14 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 15 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 16 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 17 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_txt_0528data --recover_step 18 

#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 1 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 2 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 3 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 4 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 5 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 6 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 7 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 8 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 9 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 10 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 11 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img' --task_to_learn 'qa' --num_workers 8 --max_pred 30 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_alone_img_and_cxt --recover_step 12

#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 1 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 2 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 3 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 4 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 5 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 6 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 7 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 8 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 9 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 10 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 11 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 12 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 13 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 14 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 15 &&
#CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'img|txt' --task_to_learn 'qa' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 4 --save_loss_curve --num_train_epochs 5 --output_dir tmp/qa_full_data --recover_step 16

CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_alone_txt_20choices_0528data --recover_step 1 &&
CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_alone_txt_20choices_0528data --recover_step 2 &&
CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_alone_txt_20choices_0528data --recover_step 3 &&
CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_alone_txt_20choices_0528data --recover_step 4 &&
CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_alone_txt_20choices_0528data --recover_step 5 &&
CUDA_VISIBLE_DEVICES=0 python run_webqa.py --new_segment_ids --val_loss --train_batch_size 128 --split val --answer_provided_by 'txt' --task_to_learn 'filter' --num_workers 8 --max_pred 50 --mask_prob 1.0 --learning_rate 3e-5 --gradient_accumulation_steps 8 --save_loss_curve --num_train_epochs 5 --output_dir tmp/filter_alone_txt_20choices_0528data --recover_step 6